package com.valui.common.domain;

public enum TokenReasonCode {
    PLAN_GRANT,
    TOPUP,
    ADMIN_GRANT,
    ADMIN_DEDUCT,
    CONTROLLER_BK_CHARGE,
    MONTHLY_BK_CHARGE,
    FILTER_CHARGE,
    MONTHLY_FILTER_CHARGE,
    CONTROLLER_FILTER_CHARGE,
    MONTHLY_CONTROLLER_FILTER_CHARGE,
    NOTIFICATION_SENT
}
